apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: agromarket
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672  # Puerto de RabbitMQ
      targetPort: 5672
    - protocol: TCP
      port: 15672  # Puerto de administraci√≥n (si lo deseas)
      targetPort: 15672
