apiVersion: v1
kind: Secret
metadata:
  name: agromarket-auth
  namespace: agromarket
type: Opaque
stringData:
  AUTH_USERNAME: "agroadmin"
  AUTH_PASSWORD: "agro123"
  AUTH_API_KEY: "AGRO-API-KEY-123"
  AUTH_ALLOWED_IP: "0.0.0.0/0"
  AUTH_TOKEN_SECRET: "super-secret-token"
