apiVersion: v1
kind: Service
metadata:
  name: agromarket-api-lb
  namespace: agromarket
spec:
  selector:
    app: agromarket-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
